url: "http://scattered-thoughts.net"
baseurl: ""
title: Scattered Thoughts

author:
  name: Jamie Brandon
  email: "jamie@scattered-thoughts.net"
  github: jamii
  twitter: jamiiecb
  
google_analytics: "UA-18515092-1"

timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - classes
  - code
  - JuliaCon2018

keep_files:
  - JuliaCon2018

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

gems:
  - jekyll-redirect-from